POST http://localhost:8001/member/household/save
Content-Type: application/json
token: {{token}}

{
  "name": "test",
  "idCard": "123",
  "type": "1",
  "school": "人工智能学院",
  "years": 2021,
  "room": "未分配"
}
###

GET http://localhost:8000/member/household/query-list
Accept: application/json
token: {{token}}

###