POST http://localhost:8001/member/household/save
Content-Type: application/json
token: {{token}}

{
  "name": "陈浩",
  "idCard": "21171213830",
  "type": "1",
  "year": "2021",
  "school": "人工智能学院"
}
###

GET http://localhost:8000/member/household/query-list?page=1&size=20
Accept: application/json
token: {{token}}

###